Noetic devel
PR2/pr2_simulator pull request #149
Opened 2021-02-22 07:43 UTC by davefeilseifer

these changes will allow pr2-simulator to compile in 20.04

2021-02-22 10:00 UTC, v4hn requested changes
As some of these fixes are not compatible with melodic/kinetic anymore, I'd suggest to merge the fixes into a new branch `noetic-devel` and release from there.

2021-02-22 10:00 UTC, v4hn commented on pr2_gazebo_plugins/CMakeLists.txt
> +set(CXXFLAGS -std=c++17)
```suggestion
set(CMAKE_CXX_STANDARD 17)
```

2021-02-22 10:00 UTC, v4hn commented on pr2_gazebo_plugins/CMakeLists.txt
> +find_package(orocos_kdl HINTS "/usr/share/pkgconfig")
What? Why is there a hint for pkgconfig in a cmake `find_package` call?

2021-02-22 10:00 UTC, v4hn commented on pr2_gazebo_plugins/package.xml
> -  <run_depend>orocos_kdl</run_depend>
```suggestion
  <build_depend>liborocos-kdl</build_depend>
  <run_depend>liborocos-kdl</run_depend>
```

2021-02-22 23:56 UTC, davefeilseifer commented
I'm not sure I'm able to create a new branch with the access I have, is it possible for one of you to do so?

2021-02-23 08:41 UTC, v4hn commented
> I'm not sure I'm able to create a new branch with the access I have, is it possible for one of you to do so?

Assuming you can merge pull-requests I would expect you can also push new branches.
I just pushed a noetic-devel branch as a copy of the current kinetic-devel branch and retargeted the merge request

2021-03-01 20:10 UTC, davefeilseifer commented on pr2_gazebo_plugins/CMakeLists.txt
> +find_package(orocos_kdl HINTS "/usr/share/pkgconfig")
agreed, committed change

2021-03-01 20:12 UTC, davefeilseifer reviewed
changes made in outside commits

2021-09-10 19:50 UTC, robogeekcanada commented
Thank you @davefeilseifer. I was able to run in ROS noetic with the changes proposed. If anyone is interested, I captured the steps how to do installation in this tutorial: https://github.com/robogeekcanada/pr2_noetic

This may help someone until this branch is fully committed.

2022-04-12 05:20 UTC, closed without merging